### ISSUE TITLE
Add CNPJ support

### ISSUE THREAD

**Issue by williamgueiros** [reu/cpf-rs#4]
Do you see any problem to add CNPJ information

I know the calc of verify code is the same. 

in the pass, I created the Elixir [Brcpfcnpj](https://github.com/williamgueiros/Brcpfcnpj)

But now I try to study Rust

**Comment by reu** [comment]
Hey @williamgueiros! There is another repository for the CNPJ validation: https://github.com/reu/cnpj-rs

And the verify code as far as I understood is slightly different
